// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAL1PQRKvinMRFMyygHgl9D6UaZ5h709Aw",
    authDomain: "techtrack-e3044.firebaseapp.com",
    databaseURL: "https://techtrack-e3044-default-rtdb.firebaseio.com",
    projectId: "techtrack-e3044",
    storageBucket: "techtrack-e3044.appspot.com",
    messagingSenderId: "865043473872",
    appId: "1:865043473872:web:6f8d9f6e8414fa023f45d5",
    measurementId: "G-PEXL0L9RSF",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5ThMqD80Q987Y7chLQ2pBK9s1b8nsr88',
    appId: '1:865043473872:android:e54e77ea83fe1d013f45d5',
    messagingSenderId: '865043473872',
    projectId: 'techtrack-e3044',
    databaseURL: 'https://techtrack-e3044-default-rtdb.firebaseio.com',
    storageBucket: 'techtrack-e3044.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSPXOKUSFV9GLxjGhiGIrl3vuByJqE9eg',
    appId: '1:865043473872:ios:1c2b6131d3b879243f45d5',
    messagingSenderId: '865043473872',
    projectId: 'techtrack-e3044',
    databaseURL: 'https://techtrack-e3044-default-rtdb.firebaseio.com',
    storageBucket: 'techtrack-e3044.appspot.com',
    iosClientId: '865043473872-7jg3i1ljh46i21cfeiked8j1e6n53qoq.apps.googleusercontent.com',
    iosBundleId: 'com.app.tecktrackDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL1PQRKvinMRFMyygHgl9D6UaZ5h709Aw',
    appId: '1:865043473872:web:84528f2c07ffc3833f45d5',
    messagingSenderId: '865043473872',
    projectId: 'techtrack-e3044',
    authDomain: 'techtrack-e3044.firebaseapp.com',
    databaseURL: 'https://techtrack-e3044-default-rtdb.firebaseio.com',
    storageBucket: 'techtrack-e3044.appspot.com',
    measurementId: 'G-1Y0X71PCHV',
  );
}
